name: open_fashion
description: E-commerce app.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.5 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  sms_autofill: ^2.3.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.0
  change_app_package_name: ^1.1.0
dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Tenor Sans
      fonts: 
        - asset: assets/fonts/TenorSans.ttf
          weight: 400
    - family: Bodoni Moda 28pt
      fonts: 
        - asset: assets/fonts/BodoniModa28ptBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/BodoniModa28ptBold.ttf
          weight: 700
        - asset: assets/fonts/BodoniModa28ptExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/BodoniModa28ptBlack.ttf
          weight: 900
